dist: bionic
language: python
python: '3.7'
env:
- DISTROS=ubuntu,debian,fedora
before_install:
- sudo apt-get update -qq
install:
- pip3 install ansible pyopenssl cryptography
before_script:
- make setup
script:
- make install ADD_ANSIBLE_PLAYBOOK_OPTS="--syntax-check"
- make install
- 'make install | grep -q ''changed=0.*failed=0'' && (echo ''Idempotence: PASS'' && exit 0) || (echo ''Idempotence: FAIL'' && exit 1)'
after_script:
- make teardown
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
