# roles/kafka/tasks/initialize.yml
---
- name: initialize | create data folders
  file:
    path: "{{ item.name }}/kafka"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  with_items: "{{ data_devices | default(omit) }}"
  when: "data_devices is defined and data_devices"

- meta: flush_handlers

- name: initialize | start kafka
  service:
    name: kafka
    enabled: yes
    state: started

#- name: initialize | packages
#  pip:
#    name: python-consul
#    state: present
#
#- name: initialize | service definition
#  consul:
#    host: "{{ ansible_default_ipv4.address }}"
#    port: "{{ consul_http_port | default(8500) }}"
#    service_name: kafka
#    service_port: "{{ kafka_config_port }}"
#    interval: 60s
#    script: "nc -z {{ ansible_default_ipv4.address }} {{ kafka_config_port }}"
#    tags:
#      - storage
#  when: cluster_interface is not defined
#
#- name: initialize | service definition
#  consul:
#    host: "{{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }}"
#    port: "{{ consul_http_port | default(8500) }}"
#    service_name: cassandra
#    service_port: "{{ kafka_config_port }}"
#    interval: 60s
#    script: "nc -z {{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }} {{ kafka_config_port }}"
#    tags:
#      - storage
#  when: cluster_interface is defined
